apiVersion: apps/v1
kind: Deployment
metadata:
  name: investment-service
  namespace: ruralneighbour-dev
  labels:
    app: investment-service
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: investment-service
  template:
    metadata:
      labels:
        app: investment-service
    spec:
      containers:
        - name: investment-service
          image: 127.0.0.1:32000/ruralneighbour/investment-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql://neighbor:password@rn-pg-rw:5432/investment_service"
            # Redis configuration for caching and event publishing
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: redis-secrets
                  key: redis-host
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: redis-secrets
                  key: redis-port
            - name: REDIS_URL
              value: "redis://redis-service:6379"
            # Event streams configuration
            - name: INVESTMENT_LIFECYCLE_STREAM
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: investment-lifecycle-stream
            # JWT configuration for token validation
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: jwt-secret-key
            - name: ALGORITHM
              value: "HS256"
            # Environment
            - name: ENVIRONMENT
              value: "production"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
      imagePullSecrets:
        - name: regcred
