apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: neighbor-connect-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  rules:
    - http:
        paths:
          # Auth Service
          - path: /api/v1/auth
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 80

          # User Service
          - path: /api/v1/users
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  number: 80

          # Location Service
          - path: /api/v1/locations
            pathType: Prefix
            backend:
              service:
                name: location-service
                port:
                  number: 80

          # Request Service
          - path: /api/v1/requests
            pathType: Prefix
            backend:
              service:
                name: request-service
                port:
                  number: 80

          # Payment Service
          - path: /api/v1/payments
            pathType: Prefix
            backend:
              service:
                name: payment-service
                port:
                  number: 80

          # Notification Service
          - path: /api/v1/notifications
            pathType: Prefix
            backend:
              service:
                name: notification-service
                port:
                  number: 80

          # Content Service
          - path: /api/v1/content
            pathType: Prefix
            backend:
              service:
                name: content-service
                port:
                  number: 80

          # Investment Service
          - path: /api/v1/investments
            pathType: Prefix
            backend:
              service:
                name: investment-service
                port:
                  number: 80

          # Safety Service
          - path: /api/v1/safety
            pathType: Prefix
            backend:
              service:
                name: safety-service
                port:
                  number: 80

          # API Docs (swagger-ui) - added separately under /api-docs

          # Health check endpoints
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 80

          # API Docs Portal (Swagger UI aggregator)
          - path: /api-docs
            pathType: Prefix
            backend:
              service:
                name: api-docs
                port:
                  number: 80
