apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: ruralneighbour-dev
type: Opaque
stringData:
  # 直接寫明文，Kubernetes 會自動進行 base64 編碼
  postgres-user: neighbor
  postgres-password: password
  postgres-host: rn-pg-rw
  postgres-port: "5432"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: ruralneighbour-dev
data:
  # Database names for each service
  auth-db: auth_db
  user-db: user_db
  location-db: location_db
  request-db: request_db
  payment-db: payment_db
  notification-db: notification_db
  content-db: content_db
  safety-db: safety_db
