apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-service
  namespace: ruralneighbour-dev
  labels:
    app: location-service
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-service
  template:
    metadata:
      labels:
        app: location-service
    spec:
      containers:
        - name: location-service
          image: 127.0.0.1:32000/ruralneighbour/location-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            # Database configuration
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: postgres-password
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: postgres-host
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: postgres-port
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: location-db
            - name: DATABASE_URL
              value: "postgresql://neighbor:password@rn-pg-rw:5432/location_db"
            # Redis configuration
            - name: REDIS_URL
              value: "redis://redis-service:6379"
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: redis-secrets
                  key: redis-host
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: redis-secrets
                  key: redis-port
            # JWT configuration
            - name: SECRET_KEY
              value: "your-secret-key-change-in-production"
            - name: ALGORITHM
              value: "HS256"
            # Service URLs
            - name: AUTH_SERVICE_URL
              value: "http://auth-service:80"
            - name: USER_SERVICE_URL
              value: "http://user-service:80"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
      imagePullSecrets:
        - name: regcred
