apiVersion: v1
kind: Service
metadata:
  name: request-service
  namespace: default
  labels:
    app: request-service
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: request-service

