apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: ruralneighbour-dev
  labels:
    app: user-service
    tier: backend
    version: v1
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: user-service
    version: v1

