apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: default
type: Opaque
data:
  # Base64 encoded JWT secret key - replace with actual secure key in production
  jwt-secret-key: bXlzdXBlcnNlY3VyZWp3dHNlY3JldGtleWZvcnByb2R1Y3Rpb25jaGFuZ2V0aGlz  # mysupersecurejwtsecretkeyforproductionchangethis