apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-service
  namespace: ruralneighbour-dev
  labels:
    app: content-service
    tier: backend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-service
      version: v1
  template:
    metadata:
      labels:
        app: content-service
        version: v1
    spec:
      containers:
        - name: content-service
          image: 127.0.0.1:32000/ruralneighbour/content-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            # Database configuration for PostgreSQL
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: postgres-password
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: postgres-host
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: postgres-port
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: content-db
            - name: DATABASE_URL
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)"
            # Redis configuration for caching
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: redis-secrets
                  key: redis-host
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: redis-secrets
                  key: redis-port
            - name: REDIS_URL
              value: "redis://redis-service:6379"
            # Content retention settings
            - name: CONTENT_RETENTION_DAYS
              value: "365"
            - name: ENABLE_AUTO_CLEANUP
              value: "true"
            # Admin configuration
            - name: ADMIN_ROLE_REQUIRED
              value: "true"
            # Environment
            - name: ENVIRONMENT
              value: "production"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "300m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 2
          startupProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 10
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
