apiVersion: v1
kind: Secret
metadata:
  name: rating-service-secrets
  namespace: rural-neighbour
type: Opaque
data:
  database-url: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAZGF0YWJhc2U6NTQzMi9yYXRpbmdfc2VydmljZQ== # postgresql://user:password@database:5432/rating_service
  redis-url: cmVkaXM6Ly9yZWRpczozMDAw # redis://redis:3000
  secret-key: eW91ci1zZWNyZXQta2V5LWhlcmU= # your-secret-key-here






