apiVersion: v1
kind: Service
metadata:
  name: safety-service
  namespace: ruralneighbour-dev
  labels:
    app: safety-service
    tier: backend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: safety-service




