apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-docs
  template:
    metadata:
      labels:
        app: api-docs
    spec:
      containers:
        - name: swagger-ui
          image: swaggerapi/swagger-ui:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: swagger-index
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
            - name: swagger-config
              mountPath: /usr/share/nginx/html/swagger-initializer.js
              subPath: swagger-initializer.js
      volumes:
        - name: swagger-index
          configMap:
            name: swagger-ui-config
            items:
              - key: index.html
                path: index.html
        - name: swagger-config
          configMap:
            name: swagger-ui-config
            items:
              - key: swagger-initializer.js
                path: swagger-initializer.js
